{{- if .Values.gateway.http.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.name }}-route-http
  labels:
    {{- include "quizap.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with (include "quizap.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    kind: Gateway
    sectionName: http
  hostnames:
  - {{ .Values.gateway.domain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: {{ .Values.backend.name }}
      port: {{ .Values.backend.service.port }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.frontend.name }}
      port: {{ .Values.frontend.service.port }}
{{- end }}
