apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 31437
        hostPort: 80
        protocol: TCP
      - containerPort: 31438
        hostPort: 443
