apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: quizap-frontend
  namespace: quizap-dev
spec:
  # Source configuration - points to the frontend directory
  source:
    type: Git
    git:
      url: https://github.com/adambkaplan/quizap.git
      revision: main
    contextDir: frontend
  
  # Build strategy using buildpacks
  strategy:
    name: buildpacks-v3
    kind: ClusterBuildStrategy
  
  # Output image configuration
  output:
    image: harbor-core.harbor.svc.cluster.local/quizap/frontend:latest
    insecure: true
    pushSecret: harbor
