nginx:
  service:
    type: NodePort
    nodePorts:
      - port: 31437
        listenerPort: 80
      - port: 31438
        listenerPort: 443
    nodeSelector:
      node-role.kubernetes.io/worker: ""
