name: Backend CI
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'
      - 'Makefile'
  push:
    branches:
      - main
      - release*
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'
      - 'Makefile'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Setup ko
        uses: ko-build/setup-ko@v0.9
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Download dependencies
        run: make backend-install
      - name: Build
        run: make backend-build-container IMAGE_PUSH=${{ github.event_name == 'push' }}
      - name: Test
        run: make backend-test
