name: Backend CI
on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches:
      - main
      - release*
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Download dependencies
        run: make backend-install
      - name: Build
        run: make backend-build
      - name: Test
        run: make backend-test
