name: Frontend CI
on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
      - release*
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: make frontend-install
      - name: Run eslint
        run: make frontend-lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: make frontend-install
      - name: Run tests
        run: make frontend-test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: make frontend-install
      - name: Attempt a build
        run: make frontend-build
