name: Frontend CI
on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yaml'
      - 'Makefile'
  push:
    branches:
      - main
      - release*
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yaml'
      - 'Makefile'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: make frontend-install
      - name: Run eslint
        run: make frontend-lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: make frontend-install
      - name: Run tests
        run: make frontend-test
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.9.4
      - name: Install dependencies
        run: make frontend-install
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build container with pack
        run: make frontend-build-container IMAGE_PUSH=${{ github.event_name == 'push' }}
